<?php 

require_once ('my_sql_connect.php');
echo "Starting<br>";
runQuery("DROP TABLE asset");
runQuery("CREATE TABLE asset (asset_id INT, name VARCHAR(255), asset_type_id INT, quantity INT, faction_id INT)");
runQuery("DROP TABLE asset_class");
runQuery("CREATE TABLE asset_class (asset_class_id INT, name VARCHAR(255))");
runQuery("DROP TABLE asset_type");
runQuery("CREATE TABLE asset_type (asset_type_id INT, name VARCHAR(255), visibility DOUBLE, size DOUBLE, asset_class_id INT)");
runQuery("DROP TABLE faction");
runQuery("CREATE TABLE faction (faction_id INT, name VARCHAR(255), game_id INT, user_id INT, faction_type_id INT, faction_icon_id INT)");
runQuery("DROP TABLE faction_icon");
runQuery("CREATE TABLE faction_icon (faction_icon_id INT, src VARCHAR(255))");
runQuery("DROP TABLE faction_relationship");
runQuery("CREATE TABLE faction_relationship (faction_relationship_id INT, faction_id INT, other_faction_id INT, relation DOUBLE)");
runQuery("DROP TABLE faction_type");
runQuery("CREATE TABLE faction_type (faction_type_id INT, name VARCHAR(255))");
runQuery("DROP TABLE game");
runQuery("CREATE TABLE game (game_id INT, name VARCHAR(255), turn INT)");
runQuery("DROP TABLE map");
runQuery("CREATE TABLE map (map_id INT, name VARCHAR(255))");
runQuery("DROP TABLE op");
runQuery("CREATE TABLE op (op_id INT, op_type_id INT, quantity INT, start_date VARCHAR(255), end_date VARCHAR(255), game_id INT)");
runQuery("DROP TABLE op_class");
runQuery("CREATE TABLE op_class (op_class_id INT, name VARCHAR(255))");
runQuery("DROP TABLE op_req");
runQuery("CREATE TABLE op_req (op_type_req_id INT, op_type_id INT, asset_type_id INT, required INT, consumed INT, produced INT, op_a_type_id INT)");
runQuery("DROP TABLE op_type");
runQuery("CREATE TABLE op_type (op_type_id INT, name VARCHAR(255), op_class_id INT, min_duration DOUBLE, max_duration DOUBLE, visibility DOUBLE, description VARCHAR(255), notes VARCHAR(255))");
runQuery("DROP TABLE opt_at_type");
runQuery("CREATE TABLE opt_at_type (opt_at_type_id INT, name VARCHAR(255))");
runQuery("DROP TABLE opt_opt");
runQuery("CREATE TABLE opt_opt (opt_opt_id INT, op_type_id INT, other_op_type_id INT, probability DOUBLE, quantity DOUBLE, opt_opt_type_id INT)");
runQuery("DROP TABLE opt_opt_type");
runQuery("CREATE TABLE opt_opt_type (opt_opt_type_id INT, name VARCHAR(255))");
runQuery("DROP TABLE opt_zpt");
runQuery("CREATE TABLE opt_zpt (opt_zpt_id INT, op_type_id INT, zone_property_type_id INT, quantity DOUBLE, factor DOUBLE, fade INT)");
runQuery("DROP TABLE user");
runQuery("CREATE TABLE user (user_id INT, username VARCHAR(255), password VARCHAR(255), email VARCHAR(255), guid VARCHAR(255))");
runQuery("DROP TABLE z_a");
runQuery("CREATE TABLE z_a (z_a_id INT, zone_id INT, asset_id INT)");
runQuery("DROP TABLE zone");
runQuery("CREATE TABLE zone (zone_id INT, game_id INT, zone_type_id INT, name VARCHAR(255), x INT, y INT, population INT, size INT, map_id INT)");
runQuery("DROP TABLE zone_property");
runQuery("CREATE TABLE zone_property (zone_property_id INT, zone_id INT, zone_property_type_id INT, property_value VARCHAR(255), faction_id INT)");
runQuery("DROP TABLE zone_property_type");
runQuery("CREATE TABLE zone_property_type (zone_property_type_id INT, name VARCHAR(255), per_faction INT)");
runQuery("DROP TABLE zone_type");
runQuery("CREATE TABLE zone_type (zone_type_id INT, name VARCHAR(255), logistics DOUBLE, concealment DOUBLE, population DOUBLE)");
runQuery("DELETE t FROM asset t");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, quantity, faction_id) VALUES (\"1\", \"\", \"5\", \"1\", \"1\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, quantity, faction_id) VALUES (\"2\", \"\", \"1\", \"10\", \"2\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, quantity, faction_id) VALUES (\"3\", \"\", \"6\", \"\", \"1\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, quantity, faction_id) VALUES (\"4\", \"\", \"2\", \"\", \"2\")");
runQuery("DELETE t FROM asset_class t");
runQuery("INSERT INTO asset_class (asset_class_id, name) VALUES (\"1\", \"Population\")");
runQuery("INSERT INTO asset_class (asset_class_id, name) VALUES (\"2\", \"Military Unit\")");
runQuery("INSERT INTO asset_class (asset_class_id, name) VALUES (\"3\", \"Building\")");
runQuery("INSERT INTO asset_class (asset_class_id, name) VALUES (\"4\", \"Organisation\")");
runQuery("INSERT INTO asset_class (asset_class_id, name) VALUES (\"5\", \"Intangible\")");
runQuery("DELETE t FROM asset_type t");
runQuery("INSERT INTO asset_type (asset_type_id, name, visibility, size, asset_class_id) VALUES (\"1\", \"Sympathisers\", \"\", \"\", \"1\")");
runQuery("INSERT INTO asset_type (asset_type_id, name, visibility, size, asset_class_id) VALUES (\"2\", \"Activists\", \"\", \"\", \"1\")");
runQuery("INSERT INTO asset_type (asset_type_id, name, visibility, size, asset_class_id) VALUES (\"3\", \"Militia\", \"\", \"\", \"2\")");
runQuery("INSERT INTO asset_type (asset_type_id, name, visibility, size, asset_class_id) VALUES (\"4\", \"Agents\", \"\", \"\", \"1\")");
runQuery("INSERT INTO asset_type (asset_type_id, name, visibility, size, asset_class_id) VALUES (\"5\", \"Government\", \"1\", \"\", \"4\")");
runQuery("INSERT INTO asset_type (asset_type_id, name, visibility, size, asset_class_id) VALUES (\"6\", \"Police\", \"\", \"\", \"2\")");
runQuery("INSERT INTO asset_type (asset_type_id, name, visibility, size, asset_class_id) VALUES (\"7\", \"Secret Police\", \"\", \"\", \"4\")");
runQuery("INSERT INTO asset_type (asset_type_id, name, visibility, size, asset_class_id) VALUES (\"8\", \"Arms\", \"\", \"\", \"5\")");
runQuery("INSERT INTO asset_type (asset_type_id, name, visibility, size, asset_class_id) VALUES (\"9\", \"Funds\", \"\", \"\", \"5\")");
runQuery("INSERT INTO asset_type (asset_type_id, name, visibility, size, asset_class_id) VALUES (\"10\", \"Safe house\", \"0.05\", \"\", \"3\")");
runQuery("INSERT INTO asset_type (asset_type_id, name, visibility, size, asset_class_id) VALUES (\"12\", \"Seat of government\", \"\", \"\", \"3\")");
runQuery("INSERT INTO asset_type (asset_type_id, name, visibility, size, asset_class_id) VALUES (\"13\", \"Newspaper office\", \"\", \"\", \"3\")");
runQuery("INSERT INTO asset_type (asset_type_id, name, visibility, size, asset_class_id) VALUES (\"14\", \"Radio station\", \"\", \"\", \"3\")");
runQuery("INSERT INTO asset_type (asset_type_id, name, visibility, size, asset_class_id) VALUES (\"15\", \"Embassy\", \"1\", \"\", \"3\")");
runQuery("INSERT INTO asset_type (asset_type_id, name, visibility, size, asset_class_id) VALUES (\"16\", \"Informants\", \"0.05\", \"\", \"\")");
runQuery("DELETE t FROM faction t");
runQuery("INSERT INTO faction (faction_id, name, game_id, user_id, faction_type_id, faction_icon_id) VALUES (\"1\", \"Ruling Elite\", \"10\", \"1\", \"1\", \"3\")");
runQuery("INSERT INTO faction (faction_id, name, game_id, user_id, faction_type_id, faction_icon_id) VALUES (\"2\", \"NLF\", \"10\", \"\", \"1\", \"2\")");
runQuery("INSERT INTO faction (faction_id, name, game_id, user_id, faction_type_id, faction_icon_id) VALUES (\"3\", \"US\", \"10\", \"\", \"2\", \"1\")");
runQuery("INSERT INTO faction (faction_id, name, game_id, user_id, faction_type_id, faction_icon_id) VALUES (\"4\", \"Cao Dai\", \"10\", \"\", \"1\", \"4\")");
runQuery("INSERT INTO faction (faction_id, name, game_id, user_id, faction_type_id, faction_icon_id) VALUES (\"5\", \"Binh Xuyen\", \"10\", \"\", \"1\", \"\")");
runQuery("INSERT INTO faction (faction_id, name, game_id, user_id, faction_type_id, faction_icon_id) VALUES (\"6\", \"Hoa Hao\", \"10\", \"\", \"1\", \"\")");
runQuery("INSERT INTO faction (faction_id, name, game_id, user_id, faction_type_id, faction_icon_id) VALUES (\"7\", \"Hmong\", \"10\", \"\", \"1\", \"\")");
runQuery("DELETE t FROM faction_icon t");
runQuery("INSERT INTO faction_icon (faction_icon_id, src) VALUES (\"1\", \"us.gif\")");
runQuery("INSERT INTO faction_icon (faction_icon_id, src) VALUES (\"2\", \"nlf.gif\")");
runQuery("INSERT INTO faction_icon (faction_icon_id, src) VALUES (\"3\", \"svn.gif\")");
runQuery("INSERT INTO faction_icon (faction_icon_id, src) VALUES (\"4\", \"cao.png\")");
runQuery("DELETE t FROM faction_relationship t");
runQuery("INSERT INTO faction_relationship (faction_relationship_id, faction_id, other_faction_id, relation) VALUES (\"1\", \"3\", \"2\", \"-1\")");
runQuery("INSERT INTO faction_relationship (faction_relationship_id, faction_id, other_faction_id, relation) VALUES (\"2\", \"2\", \"3\", \"-1\")");
runQuery("INSERT INTO faction_relationship (faction_relationship_id, faction_id, other_faction_id, relation) VALUES (\"3\", \"1\", \"2\", \"-0.8\")");
runQuery("INSERT INTO faction_relationship (faction_relationship_id, faction_id, other_faction_id, relation) VALUES (\"4\", \"2\", \"1\", \"-1\")");
runQuery("INSERT INTO faction_relationship (faction_relationship_id, faction_id, other_faction_id, relation) VALUES (\"5\", \"1\", \"5\", \"-0.5\")");
runQuery("INSERT INTO faction_relationship (faction_relationship_id, faction_id, other_faction_id, relation) VALUES (\"6\", \"5\", \"1\", \"-0.5\")");
runQuery("DELETE t FROM faction_type t");
runQuery("INSERT INTO faction_type (faction_type_id, name) VALUES (\"1\", \"Indigenous\")");
runQuery("INSERT INTO faction_type (faction_type_id, name) VALUES (\"2\", \"Foreign Sponsor\")");
runQuery("INSERT INTO faction_type (faction_type_id, name) VALUES (\"3\", \"Colonial Power\")");
runQuery("INSERT INTO faction_type (faction_type_id, name) VALUES (\"4\", \"Colonial Settlers\")");
runQuery("DELETE t FROM game t");
runQuery("INSERT INTO game (game_id, name, turn) VALUES (\"10\", \"VN 1955\", \"1\")");
runQuery("DELETE t FROM map t");
runQuery("INSERT INTO map (map_id, name) VALUES (\"1\", \"Geographical\")");
runQuery("INSERT INTO map (map_id, name) VALUES (\"2\", \"Political\")");
runQuery("DELETE t FROM op t");
runQuery("INSERT INTO op (op_id, op_type_id, quantity, start_date, end_date, game_id) VALUES (\"1\", \"\", \"\", \"\", \"\", \"\")");
runQuery("DELETE t FROM op_class t");
runQuery("INSERT INTO op_class (op_class_id, name) VALUES (\"1\", \"Preparation\")");
runQuery("INSERT INTO op_class (op_class_id, name) VALUES (\"2\", \"Outcome\")");
runQuery("DELETE t FROM op_req t");
runQuery("INSERT INTO op_req (op_type_req_id, op_type_id, asset_type_id, required, consumed, produced, op_a_type_id) VALUES (\"1\", \"1\", \"2\", \"3\", \"\", \"1\", \"1\")");
runQuery("INSERT INTO op_req (op_type_req_id, op_type_id, asset_type_id, required, consumed, produced, op_a_type_id) VALUES (\"2\", \"1\", \"1\", \"100\", \"1\", \"\", \"1\")");
runQuery("INSERT INTO op_req (op_type_req_id, op_type_id, asset_type_id, required, consumed, produced, op_a_type_id) VALUES (\"3\", \"2\", \"1\", \"1000\", \"\", \"\", \"1\")");
runQuery("INSERT INTO op_req (op_type_req_id, op_type_id, asset_type_id, required, consumed, produced, op_a_type_id) VALUES (\"4\", \"2\", \"2\", \"100\", \"\", \"\", \"1\")");
runQuery("INSERT INTO op_req (op_type_req_id, op_type_id, asset_type_id, required, consumed, produced, op_a_type_id) VALUES (\"5\", \"3\", \"2\", \"10\", \"\", \"\", \"\")");
runQuery("INSERT INTO op_req (op_type_req_id, op_type_id, asset_type_id, required, consumed, produced, op_a_type_id) VALUES (\"6\", \"5\", \"2\", \"10\", \"10\", \"\", \"\")");
runQuery("INSERT INTO op_req (op_type_req_id, op_type_id, asset_type_id, required, consumed, produced, op_a_type_id) VALUES (\"7\", \"5\", \"3\", \"\", \"\", \"10\", \"\")");
runQuery("INSERT INTO op_req (op_type_req_id, op_type_id, asset_type_id, required, consumed, produced, op_a_type_id) VALUES (\"8\", \"5\", \"8\", \"\", \"10\", \"\", \"\")");
runQuery("INSERT INTO op_req (op_type_req_id, op_type_id, asset_type_id, required, consumed, produced, op_a_type_id) VALUES (\"9\", \"6\", \"2\", \"10\", \"\", \"\", \"\")");
runQuery("INSERT INTO op_req (op_type_req_id, op_type_id, asset_type_id, required, consumed, produced, op_a_type_id) VALUES (\"10\", \"6\", \"9\", \"\", \"10\", \"\", \"\")");
runQuery("INSERT INTO op_req (op_type_req_id, op_type_id, asset_type_id, required, consumed, produced, op_a_type_id) VALUES (\"11\", \"6\", \"10\", \"\", \"\", \"1\", \"\")");
runQuery("INSERT INTO op_req (op_type_req_id, op_type_id, asset_type_id, required, consumed, produced, op_a_type_id) VALUES (\"12\", \"7\", \"8\", \"\", \"\", \"1\", \"\")");
runQuery("INSERT INTO op_req (op_type_req_id, op_type_id, asset_type_id, required, consumed, produced, op_a_type_id) VALUES (\"13\", \"7\", \"9\", \"\", \"1\", \"\", \"\")");
runQuery("INSERT INTO op_req (op_type_req_id, op_type_id, asset_type_id, required, consumed, produced, op_a_type_id) VALUES (\"15\", \"8\", \"5\", \"\", \"\", \"1\", \"\")");
runQuery("INSERT INTO op_req (op_type_req_id, op_type_id, asset_type_id, required, consumed, produced, op_a_type_id) VALUES (\"16\", \"9\", \"5\", \"1\", \"\", \"\", \"\")");
runQuery("INSERT INTO op_req (op_type_req_id, op_type_id, asset_type_id, required, consumed, produced, op_a_type_id) VALUES (\"17\", \"3\", \"9\", \"\", \"\", \"1\", \"\")");
runQuery("INSERT INTO op_req (op_type_req_id, op_type_id, asset_type_id, required, consumed, produced, op_a_type_id) VALUES (\"18\", \"10\", \"3\", \"50\", \"\", \"\", \"\")");
runQuery("INSERT INTO op_req (op_type_req_id, op_type_id, asset_type_id, required, consumed, produced, op_a_type_id) VALUES (\"19\", \"13\", \"5\", \"1\", \"\", \"\", \"\")");
runQuery("INSERT INTO op_req (op_type_req_id, op_type_id, asset_type_id, required, consumed, produced, op_a_type_id) VALUES (\"20\", \"14\", \"5\", \"1\", \"\", \"\", \"\")");
runQuery("INSERT INTO op_req (op_type_req_id, op_type_id, asset_type_id, required, consumed, produced, op_a_type_id) VALUES (\"21\", \"15\", \"5\", \"1\", \"\", \"\", \"\")");
runQuery("INSERT INTO op_req (op_type_req_id, op_type_id, asset_type_id, required, consumed, produced, op_a_type_id) VALUES (\"22\", \"17\", \"3\", \"50\", \"\", \"\", \"\")");
runQuery("DELETE t FROM op_type t");
runQuery("INSERT INTO op_type (op_type_id, name, op_class_id, min_duration, max_duration, visibility, description, notes) VALUES (\"1\", \"Recruit activists\", \"1\", \"\", \"-1\", \"0.1\", \"\", \"\")");
runQuery("INSERT INTO op_type (op_type_id, name, op_class_id, min_duration, max_duration, visibility, description, notes) VALUES (\"2\", \"Peaceful demonstration\", \"1\", \"1\", \"10\", \"0.5\", \"\", \"\")");
runQuery("INSERT INTO op_type (op_type_id, name, op_class_id, min_duration, max_duration, visibility, description, notes) VALUES (\"3\", \"Fund raise\", \"1\", \"\", \"-1\", \"0.1\", \"\", \"\")");
runQuery("INSERT INTO op_type (op_type_id, name, op_class_id, min_duration, max_duration, visibility, description, notes) VALUES (\"4\", \"Agitate\", \"\", \"\", \"-1\", \"0.2\", \"\", \"\")");
runQuery("INSERT INTO op_type (op_type_id, name, op_class_id, min_duration, max_duration, visibility, description, notes) VALUES (\"5\", \"Raise militia\", \"1\", \"1\", \"\", \"0.2\", \"\", \"\")");
runQuery("INSERT INTO op_type (op_type_id, name, op_class_id, min_duration, max_duration, visibility, description, notes) VALUES (\"6\", \"Build safe house\", \"1\", \"10\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO op_type (op_type_id, name, op_class_id, min_duration, max_duration, visibility, description, notes) VALUES (\"7\", \"Acquire Arms\", \"\", \"10\", \"\", \"0.1\", \"\", \"\")");
runQuery("INSERT INTO op_type (op_type_id, name, op_class_id, min_duration, max_duration, visibility, description, notes) VALUES (\"8\", \"Form Government\", \"\", \"20\", \"\", \"\", \"\", \"Needs min. Admin control. Zone specific. Removes asset from any other in that zone\")");
runQuery("INSERT INTO op_type (op_type_id, name, op_class_id, min_duration, max_duration, visibility, description, notes) VALUES (\"9\", \"Curfew\", \"\", \"\", \"-1\", \"\", \"Impose curfew\", \"\")");
runQuery("INSERT INTO op_type (op_type_id, name, op_class_id, min_duration, max_duration, visibility, description, notes) VALUES (\"10\", \"Roadblocks\", \"\", \"\", \"-1\", \"0.7\", \"\", \"Increases physical control (decrease popularity?)\")");
runQuery("INSERT INTO op_type (op_type_id, name, op_class_id, min_duration, max_duration, visibility, description, notes) VALUES (\"11\", \"Bad press\", \"\", \"\", \"-1\", \"\", \"Faction is receiving negative media coverage\", \"Decreases legitimacy and popularity\")");
runQuery("INSERT INTO op_type (op_type_id, name, op_class_id, min_duration, max_duration, visibility, description, notes) VALUES (\"12\", \"Expel reporters\", \"\", \"1\", \"1\", \"\", \"\", \"Decreases legitimacy but counteracts bad press. Requires high physical control\")");
runQuery("INSERT INTO op_type (op_type_id, name, op_class_id, min_duration, max_duration, visibility, description, notes) VALUES (\"13\", \"Hold election\", \"\", \"30\", \"30\", \"1\", \"\", \"\")");
runQuery("INSERT INTO op_type (op_type_id, name, op_class_id, min_duration, max_duration, visibility, description, notes) VALUES (\"14\", \"Declare martial law\", \"\", \"\", \"-1\", \"\", \"\", \"\")");
runQuery("INSERT INTO op_type (op_type_id, name, op_class_id, min_duration, max_duration, visibility, description, notes) VALUES (\"15\", \"False coup\", \"\", \"10\", \"10\", \"\", \"\", \"\")");
runQuery("INSERT INTO op_type (op_type_id, name, op_class_id, min_duration, max_duration, visibility, description, notes) VALUES (\"16\", \"False coup discovered\", \"\", \"1\", \"1\", \"\", \"\", \"\")");
runQuery("INSERT INTO op_type (op_type_id, name, op_class_id, min_duration, max_duration, visibility, description, notes) VALUES (\"17\", \"Seize building\", \"\", \"1\", \"1\", \"1\", \"Targets an asset - likely to result in conflict, Seize building is a counter.\", \"\")");
runQuery("DELETE t FROM opt_at_type t");
runQuery("INSERT INTO opt_at_type (opt_at_type_id, name) VALUES (\"1\", \"Requires\")");
runQuery("INSERT INTO opt_at_type (opt_at_type_id, name) VALUES (\"2\", \"Produces\")");
runQuery("DELETE t FROM opt_opt t");
runQuery("INSERT INTO opt_opt (opt_opt_id, op_type_id, other_op_type_id, probability, quantity, opt_opt_type_id) VALUES (\"1\", \"15\", \"16\", \"0.1\", \"\", \"\")");
runQuery("DELETE t FROM opt_opt_type t");
runQuery("INSERT INTO opt_opt_type (opt_opt_type_id, name) VALUES (\"1\", \"Outcome\")");
runQuery("INSERT INTO opt_opt_type (opt_opt_type_id, name) VALUES (\"2\", \"Counter\")");
runQuery("INSERT INTO opt_opt_type (opt_opt_type_id, name) VALUES (\"3\", \"Modifies\")");
runQuery("DELETE t FROM opt_zpt t");
runQuery("INSERT INTO opt_zpt (opt_zpt_id, op_type_id, zone_property_type_id, quantity, factor, fade) VALUES (\"1\", \"11\", \"7\", \"-1\", \"\", \"\")");
runQuery("INSERT INTO opt_zpt (opt_zpt_id, op_type_id, zone_property_type_id, quantity, factor, fade) VALUES (\"2\", \"11\", \"5\", \"-1\", \"\", \"\")");
runQuery("INSERT INTO opt_zpt (opt_zpt_id, op_type_id, zone_property_type_id, quantity, factor, fade) VALUES (\"3\", \"6\", \"9\", \"1\", \"\", \"\")");
runQuery("INSERT INTO opt_zpt (opt_zpt_id, op_type_id, zone_property_type_id, quantity, factor, fade) VALUES (\"4\", \"9\", \"3\", \"\", \"1.2\", \"1\")");
runQuery("INSERT INTO opt_zpt (opt_zpt_id, op_type_id, zone_property_type_id, quantity, factor, fade) VALUES (\"5\", \"9\", \"5\", \"\", \"0.9\", \"1\")");
runQuery("INSERT INTO opt_zpt (opt_zpt_id, op_type_id, zone_property_type_id, quantity, factor, fade) VALUES (\"6\", \"14\", \"3\", \"\", \"1.5\", \"1\")");
runQuery("INSERT INTO opt_zpt (opt_zpt_id, op_type_id, zone_property_type_id, quantity, factor, fade) VALUES (\"7\", \"14\", \"5\", \"\", \"0.8\", \"1\")");
runQuery("INSERT INTO opt_zpt (opt_zpt_id, op_type_id, zone_property_type_id, quantity, factor, fade) VALUES (\"8\", \"14\", \"7\", \"\", \"0.9\", \"1\")");
runQuery("INSERT INTO opt_zpt (opt_zpt_id, op_type_id, zone_property_type_id, quantity, factor, fade) VALUES (\"9\", \"12\", \"7\", \"-1\", \"\", \"\")");
runQuery("DELETE t FROM user t");
runQuery("INSERT INTO user (user_id, username, password, email, guid) VALUES (\"1\", \"aidan\", \"test\", \"\", \"aaa\")");
runQuery("DELETE t FROM z_a t");
runQuery("INSERT INTO z_a (z_a_id, zone_id, asset_id) VALUES (\"1\", \"13\", \"2\")");
runQuery("INSERT INTO z_a (z_a_id, zone_id, asset_id) VALUES (\"2\", \"1\", \"3\")");
runQuery("INSERT INTO z_a (z_a_id, zone_id, asset_id) VALUES (\"3\", \"4\", \"4\")");
runQuery("DELETE t FROM zone t");
runQuery("INSERT INTO zone (zone_id, game_id, zone_type_id, name, x, y, population, size, map_id) VALUES (\"1\", \"10\", \"1\", \"Saigon\", \"427\", \"742\", \"3000000\", \"\", \"\")");
runQuery("INSERT INTO zone (zone_id, game_id, zone_type_id, name, x, y, population, size, map_id) VALUES (\"2\", \"10\", \"1\", \"Tay Ninh City\", \"155\", \"497\", \"100000\", \"\", \"\")");
runQuery("INSERT INTO zone (zone_id, game_id, zone_type_id, name, x, y, population, size, map_id) VALUES (\"3\", \"10\", \"1\", \"Dau Tieng\", \"343\", \"491\", \"50000\", \"\", \"\")");
runQuery("INSERT INTO zone (zone_id, game_id, zone_type_id, name, x, y, population, size, map_id) VALUES (\"4\", \"10\", \"1\", \"Cu Chi\", \"383\", \"645\", \"40000\", \"\", \"\")");
runQuery("INSERT INTO zone (zone_id, game_id, zone_type_id, name, x, y, population, size, map_id) VALUES (\"5\", \"10\", \"2\", \"Ho Bo Woods\", \"354\", \"587\", \"200\", \"\", \"\")");
runQuery("INSERT INTO zone (zone_id, game_id, zone_type_id, name, x, y, population, size, map_id) VALUES (\"6\", \"10\", \"2\", \"Boi Loi Woods\", \"404\", \"614\", \"200\", \"\", \"\")");
runQuery("INSERT INTO zone (zone_id, game_id, zone_type_id, name, x, y, population, size, map_id) VALUES (\"7\", \"10\", \"4\", \"Filhol Plantation\", \"441\", \"647\", \"500\", \"\", \"\")");
runQuery("INSERT INTO zone (zone_id, game_id, zone_type_id, name, x, y, population, size, map_id) VALUES (\"8\", \"10\", \"4\", \"Ben Cui Plantation\", \"150\", \"451\", \"1000\", \"\", \"\")");
runQuery("INSERT INTO zone (zone_id, game_id, zone_type_id, name, x, y, population, size, map_id) VALUES (\"9\", \"10\", \"4\", \"Michelin Plantation\", \"423\", \"515\", \"1000\", \"\", \"\")");
runQuery("INSERT INTO zone (zone_id, game_id, zone_type_id, name, x, y, population, size, map_id) VALUES (\"10\", \"10\", \"5\", \"Nui Ba Den\", \"153\", \"431\", \"100\", \"\", \"\")");
runQuery("INSERT INTO zone (zone_id, game_id, zone_type_id, name, x, y, population, size, map_id) VALUES (\"11\", \"10\", \"6\", \"Highway 22\", \"235\", \"547\", \"\", \"\", \"\")");
runQuery("INSERT INTO zone (zone_id, game_id, zone_type_id, name, x, y, population, size, map_id) VALUES (\"12\", \"10\", \"7\", \"Plain of Reeds\", \"238\", \"683\", \"1000\", \"\", \"\")");
runQuery("INSERT INTO zone (zone_id, game_id, zone_type_id, name, x, y, population, size, map_id) VALUES (\"13\", \"10\", \"3\", \"Hau Nghia\", \"310\", \"663\", \"100000\", \"\", \"\")");
runQuery("INSERT INTO zone (zone_id, game_id, zone_type_id, name, x, y, population, size, map_id) VALUES (\"14\", \"10\", \"3\", \"Binh Duong\", \"402\", \"560\", \"100000\", \"\", \"\")");
runQuery("DELETE t FROM zone_property t");
runQuery("DELETE t FROM zone_property_type t");
runQuery("INSERT INTO zone_property_type (zone_property_type_id, name, per_faction) VALUES (\"1\", \"Population\", \"0\")");
runQuery("INSERT INTO zone_property_type (zone_property_type_id, name, per_faction) VALUES (\"2\", \"Prosperity\", \"0\")");
runQuery("INSERT INTO zone_property_type (zone_property_type_id, name, per_faction) VALUES (\"3\", \"Physical Control\", \"1\")");
runQuery("INSERT INTO zone_property_type (zone_property_type_id, name, per_faction) VALUES (\"4\", \"Administrative Control\", \"1\")");
runQuery("INSERT INTO zone_property_type (zone_property_type_id, name, per_faction) VALUES (\"5\", \"Popularity\", \"1\")");
runQuery("INSERT INTO zone_property_type (zone_property_type_id, name, per_faction) VALUES (\"6\", \"Income\", \"1\")");
runQuery("INSERT INTO zone_property_type (zone_property_type_id, name, per_faction) VALUES (\"7\", \"Legitimacy\", \"1\")");
runQuery("INSERT INTO zone_property_type (zone_property_type_id, name, per_faction) VALUES (\"8\", \"Intelligence\", \"1\")");
runQuery("INSERT INTO zone_property_type (zone_property_type_id, name, per_faction) VALUES (\"9\", \"Protection\", \"1\")");
runQuery("DELETE t FROM zone_type t");
runQuery("INSERT INTO zone_type (zone_type_id, name, logistics, concealment, population) VALUES (\"1\", \"Urban\", \"7\", \"5\", \"10\")");
runQuery("INSERT INTO zone_type (zone_type_id, name, logistics, concealment, population) VALUES (\"2\", \"Forest\", \"3\", \"8\", \"1\")");
runQuery("INSERT INTO zone_type (zone_type_id, name, logistics, concealment, population) VALUES (\"3\", \"Rural\", \"5\", \"4\", \"3\")");
runQuery("INSERT INTO zone_type (zone_type_id, name, logistics, concealment, population) VALUES (\"4\", \"Plantation\", \"5\", \"5\", \"1\")");
runQuery("INSERT INTO zone_type (zone_type_id, name, logistics, concealment, population) VALUES (\"5\", \"Mountain\", \"2\", \"9\", \"1\")");
runQuery("INSERT INTO zone_type (zone_type_id, name, logistics, concealment, population) VALUES (\"6\", \"Road\", \"9\", \"2\", \"1\")");
runQuery("INSERT INTO zone_type (zone_type_id, name, logistics, concealment, population) VALUES (\"7\", \"Marsh\", \"3\", \"6\", \"1\")");


function runQuery($strSql){
	if (mysql_query($strSql))
	  {
	  echo "Ran query" . $strSql . "<br>";
	  }
	else
	  {
	  echo "Error running query: " . mysql_error() . "<br>";
	  }
}

?>