<?php
require_once ('my_sql_connect.php');
echo 'Starting<br>';
runQuery("DROP TABLE asset");
runQuery("CREATE TABLE asset (asset_id INT, name VARCHAR(255), asset_type_id INT, zone_id INT, parent_asset_id INT, command_id INT, x DOUBLE, y DOUBLE, morale_id INT)");
runQuery("DROP TABLE asset_category");
runQuery("CREATE TABLE asset_category (asset_category_id INT, name VARCHAR(255))");
runQuery("DROP TABLE asset_type");
runQuery("CREATE TABLE asset_type (asset_type_id INT, name VARCHAR(255), asset_category_id INT, visibility INT, order_seq INT, css_class VARCHAR(255))");
runQuery("DROP TABLE channel");
runQuery("CREATE TABLE channel (channel_id INT, name VARCHAR(255), zone_id INT, faction_id INT)");
runQuery("DROP TABLE command");
runQuery("CREATE TABLE command (command_id INT, user_id INT, faction_id INT, name VARCHAR(255), seniority INT, map_id INT, parent_command_id INT, zone_id INT)");
runQuery("DROP TABLE event_type");
runQuery("CREATE TABLE event_type (event_type_id INT, name VARCHAR(255))");
runQuery("DROP TABLE faction");
runQuery("CREATE TABLE faction (faction_id INT, name VARCHAR(255), game_id INT, faction_icon_id INT)");
runQuery("DROP TABLE game");
runQuery("CREATE TABLE game (game_id INT, name VARCHAR(255), turn INT, last_update DATETIME)");
runQuery("DROP TABLE map");
runQuery("CREATE TABLE map (map_id INT, name VARCHAR(255), width INT, height INT, background VARCHAR(255), x DOUBLE, y DOUBLE, scale DOUBLE, zone_id INT)");
runQuery("DROP TABLE message");
runQuery("CREATE TABLE message (message_id INT, from_command_id INT, zone_id INT, content VARCHAR(255), channel_id INT, x DOUBLE, y DOUBLE, message_type_id INT, time_sent DATETIME)");
runQuery("DROP TABLE message_type");
runQuery("CREATE TABLE message_type (message_type_id INT, name VARCHAR(255))");
runQuery("DROP TABLE model_type");
runQuery("CREATE TABLE model_type (model_type_id INT, name VARCHAR(255), m INT, ws INT, bs INT, s INT, t INT, w INT, i INT, a INT, ld INT, intel INT, cl INT, wp INT, description VARCHAR(255))");
runQuery("DROP TABLE morale");
runQuery("CREATE TABLE morale (morale_id INT, name VARCHAR(255), rules VARCHAR(255))");
runQuery("DROP TABLE user");
runQuery("CREATE TABLE user (user_id INT, username VARCHAR(255), guid VARCHAR(255))");
runQuery("DROP TABLE z_z");
runQuery("CREATE TABLE z_z (z_z_id INT, first_zone_id INT, second_zone_id INT, capacity INT, frequency INT, name VARCHAR(255))");
runQuery("DROP TABLE zone");
runQuery("CREATE TABLE zone (zone_id INT, game_id INT, zone_type_id INT, name VARCHAR(255), x DOUBLE, y DOUBLE, map_id INT, parent_zone_id INT, width DOUBLE, height DOUBLE, scale INT)");
runQuery("DROP TABLE zone_type");
runQuery("CREATE TABLE zone_type (zone_type_id INT, name VARCHAR(255), icon VARCHAR(255))");
runQuery("DELETE t FROM asset t");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"1\", \"\", \"8\", \"2\", \"0\", \"3\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"2\", \"\", \"9\", \"\", \"1\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"3\", \"\", \"10\", \"\", \"1\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"4\", \"\", \"7\", \"\", \"1\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"5\", \"\", \"7\", \"\", \"1\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"6\", \"\", \"7\", \"\", \"1\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"7\", \"\", \"13\", \"8\", \"0\", \"3\", \"250\", \"210\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"8\", \"CC +1\", \"12\", \"\", \"7\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"9\", \"\", \"8\", \"\", \"7\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"10\", \"\", \"8\", \"\", \"7\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"11\", \"\", \"8\", \"\", \"7\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"12\", \"\", \"10\", \"8\", \"0\", \"3\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"13\", \"\", \"10\", \"8\", \"0\", \"3\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"14\", \"\", \"7\", \"\", \"9\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"15\", \"\", \"7\", \"\", \"9\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"16\", \"\", \"7\", \"\", \"9\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"17\", \"\", \"7\", \"\", \"10\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"18\", \"\", \"7\", \"\", \"10\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"19\", \"\", \"7\", \"\", \"10\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"20\", \"\", \"7\", \"\", \"11\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"21\", \"\", \"7\", \"\", \"11\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"22\", \"\", \"7\", \"\", \"11\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"23\", \"North Bridge\", \"1\", \"\", \"\", \"\", \"498\", \"196\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"24\", \"Railway Bridge\", \"1\", \"\", \"\", \"\", \"244\", \"400\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"25\", \"\", \"3\", \"\", \"\", \"\", \"634\", \"228\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"26\", \"\", \"2\", \"1\", \"\", \"14\", \"400\", \"140\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"27\", \"South Bridge\", \"1\", \"\", \"\", \"\", \"315\", \"476\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"28\", \"Centre Bridge\", \"1\", \"\", \"\", \"\", \"466\", \"297\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"29\", \"\", \"2\", \"4\", \"\", \"14\", \"486\", \"317\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"30\", \"1st FallschirmJager\", \"13\", \"4\", \"\", \"4\", \"500\", \"310\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"31\", \"\", \"11\", \"4\", \"\", \"4\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"32\", \"\", \"6\", \"4\", \"\", \"4\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"33\", \"1st FsJg Platoon\", \"8\", \"\", \"30\", \"\", \"\", \"\", \"3\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"34\", \"2nd FsJg Platoon\", \"8\", \"\", \"30\", \"\", \"\", \"\", \"3\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"35\", \"\", \"10\", \"\", \"30\", \"\", \"\", \"\", \"3\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"36\", \"\", \"13\", \"8\", \"0\", \"5\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"37\", \"\", \"8\", \"\", \"36\", \"\", \"\", \"0\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"38\", \"\", \"8\", \"\", \"36\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"39\", \"\", \"8\", \"\", \"36\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"40\", \"\", \"7\", \"\", \"37\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"41\", \"\", \"7\", \"\", \"37\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"42\", \"\", \"7\", \"\", \"37\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"43\", \"\", \"9\", \"\", \"37\", \"\", \"\", \"0\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"44\", \"(+2)\", \"12\", \"\", \"30\", \"\", \"\", \"\", \"3\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"45\", \"\", \"10\", \"\", \"30\", \"\", \"\", \"\", \"3\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"46\", \"3rd FsJg Platoon\", \"8\", \"\", \"30\", \"\", \"\", \"\", \"3\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"47\", \"(+2) PC\", \"9\", \"\", \"33\", \"\", \"\", \"\", \"3\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"48\", \"\", \"7\", \"\", \"33\", \"\", \"\", \"\", \"3\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"49\", \"\", \"7\", \"\", \"33\", \"\", \"\", \"\", \"3\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"50\", \"\", \"7\", \"\", \"33\", \"\", \"\", \"\", \"3\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"51\", \"+1 PC\", \"9\", \"\", \"34\", \"\", \"\", \"\", \"3\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"52\", \"\", \"7\", \"\", \"34\", \"\", \"\", \"\", \"3\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"53\", \"\", \"7\", \"\", \"34\", \"\", \"\", \"\", \"3\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"54\", \"\", \"7\", \"\", \"34\", \"\", \"\", \"0\", \"3\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"55\", \"+1 PC\", \"9\", \"\", \"46\", \"\", \"\", \"\", \"3\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"56\", \"\", \"7\", \"\", \"46\", \"\", \"\", \"\", \"3\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"57\", \"\", \"7\", \"\", \"46\", \"\", \"\", \"\", \"3\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"58\", \"\", \"7\", \"\", \"46\", \"\", \"\", \"\", \"3\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"59\", \"1/4th A\", \"13\", \"3\", \"\", \"6\", \"\", \"\", \"2\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"60\", \"+2 CC\", \"12\", \"\", \"59\", \"\", \"\", \"\", \"2\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"61\", \"\", \"10\", \"\", \"59\", \"\", \"\", \"\", \"2\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"62\", \"\", \"23\", \"\", \"59\", \"\", \"\", \"\", \"2\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"63\", \"\", \"24\", \"\", \"59\", \"\", \"\", \"\", \"2\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"64\", \"1st Platoon\", \"8\", \"\", \"59\", \"\", \"\", \"\", \"2\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"65\", \"2nd Platoon\", \"8\", \"\", \"59\", \"\", \"\", \"\", \"2\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"66\", \"3rd Platoon\", \"8\", \"\", \"59\", \"\", \"\", \"\", \"1\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"67\", \"+2 PC\", \"9\", \"\", \"64\", \"\", \"\", \"\", \"2\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"68\", \"\", \"7\", \"\", \"64\", \"\", \"\", \"\", \"2\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"69\", \"\", \"7\", \"\", \"64\", \"\", \"\", \"\", \"2\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"70\", \"\", \"7\", \"\", \"64\", \"\", \"\", \"\", \"2\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"71\", \"+1 PC\", \"9\", \"\", \"65\", \"\", \"\", \"\", \"2\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"72\", \"\", \"7\", \"\", \"65\", \"\", \"\", \"\", \"2\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"73\", \"\", \"7\", \"\", \"65\", \"\", \"\", \"\", \"2\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"74\", \"\", \"7\", \"\", \"65\", \"\", \"\", \"\", \"2\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"75\", \"+1 PC\", \"9\", \"\", \"66\", \"\", \"\", \"\", \"1\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"76\", \"\", \"7\", \"\", \"66\", \"\", \"\", \"\", \"1\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"77\", \"\", \"7\", \"\", \"66\", \"\", \"\", \"\", \"1\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"78\", \"\", \"7\", \"\", \"66\", \"\", \"\", \"\", \"1\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"79\", \"\", \"8\", \"3\", \"\", \"12\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"80\", \"+1 PC\", \"9\", \"\", \"79\", \"\", \"\", \"\", \"1\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"81\", \"\", \"7\", \"\", \"79\", \"\", \"\", \"\", \"1\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"82\", \"\", \"7\", \"\", \"79\", \"\", \"\", \"\", \"1\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"83\", \"1/4th B\", \"13\", \"2\", \"92\", \"10\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"84\", \"1/4th C\", \"13\", \"2\", \"92\", \"10\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"85\", \"2/4th C\", \"13\", \"7\", \"93\", \"2\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"86\", \"2/4th B\", \"13\", \"7\", \"93\", \"2\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"88\", \"+1CC\", \"12\", \"\", \"86\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"89\", \"\", \"8\", \"\", \"86\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"90\", \"\", \"8\", \"\", \"86\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"91\", \"\", \"8\", \"\", \"86\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"92\", \"1/4th Infantry\", \"16\", \"\", \"94\", \"2\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"93\", \"2/4th Infantry\", \"16\", \"\", \"94\", \"2\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"94\", \"4th\", \"28\", \"1\", \"\", \"14\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"95\", \"+2 CC\", \"12\", \"\", \"83\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"96\", \"\", \"8\", \"\", \"83\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"97\", \"\", \"8\", \"\", \"83\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"98\", \"\", \"8\", \"\", \"83\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"99\", \"+2 CC Braun\", \"12\", \"\", \"84\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"100\", \"\", \"8\", \"\", \"84\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"101\", \"\", \"8\", \"\", \"84\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"102\", \"\", \"8\", \"\", \"84\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"103\", \"\", \"7\", \"\", \"100\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"104\", \"\", \"7\", \"\", \"100\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"105\", \"\", \"7\", \"\", \"100\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"106\", \"\", \"7\", \"\", \"98\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"107\", \"\", \"7\", \"\", \"98\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"108\", \"\", \"7\", \"\", \"98\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"109\", \"\", \"7\", \"\", \"97\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"110\", \"\", \"7\", \"\", \"97\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"111\", \"\", \"7\", \"\", \"97\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"112\", \"\", \"9\", \"\", \"96\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"113\", \"\", \"7\", \"\", \"96\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"114\", \"\", \"7\", \"\", \"96\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"115\", \"\", \"7\", \"\", \"96\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"116\", \"\", \"9\", \"\", \"97\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"117\", \"\", \"9\", \"\", \"98\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"118\", \"\", \"9\", \"\", \"100\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"119\", \"\", \"9\", \"\", \"101\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"120\", \"\", \"7\", \"\", \"101\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"121\", \"\", \"7\", \"\", \"101\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"122\", \"\", \"7\", \"\", \"101\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"123\", \"\", \"9\", \"\", \"102\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"124\", \"\", \"7\", \"\", \"102\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"125\", \"\", \"7\", \"\", \"102\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"126\", \"\", \"7\", \"\", \"102\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"127\", \"\", \"17\", \"7\", \"92\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"128\", \"3/4th Infantry\", \"16\", \"9\", \"94\", \"16\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"129\", \"3/4th A\", \"13\", \"8\", \"128\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"130\", \"3/4th B\", \"13\", \"3\", \"128\", \"8\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"131\", \"3/4th C\", \"13\", \"3\", \"128\", \"8\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"132\", \"\", \"12\", \"\", \"129\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"133\", \"\", \"8\", \"\", \"129\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"134\", \"\", \"8\", \"\", \"129\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"135\", \"\", \"8\", \"\", \"129\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"136\", \"\", \"12\", \"\", \"130\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"137\", \"\", \"10\", \"\", \"130\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"138\", \"\", \"8\", \"\", \"130\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"139\", \"\", \"8\", \"\", \"130\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"140\", \"\", \"8\", \"\", \"130\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"141\", \"\", \"12\", \"\", \"131\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"142\", \"\", \"8\", \"\", \"131\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"143\", \"\", \"8\", \"\", \"131\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO asset (asset_id, name, asset_type_id, zone_id, parent_asset_id, command_id, x, y, morale_id) VALUES (\"144\", \"\", \"8\", \"\", \"131\", \"\", \"\", \"\", \"\")");
runQuery("DELETE t FROM asset_category t");
runQuery("INSERT INTO asset_category (asset_category_id, name) VALUES (\"1\", \"Building\")");
runQuery("INSERT INTO asset_category (asset_category_id, name) VALUES (\"2\", \"Unit\")");
runQuery("DELETE t FROM asset_type t");
runQuery("INSERT INTO asset_type (asset_type_id, name, asset_category_id, visibility, order_seq, css_class) VALUES (\"1\", \"Bridge\", \"1\", \"1\", \"\", \"\")");
runQuery("INSERT INTO asset_type (asset_type_id, name, asset_category_id, visibility, order_seq, css_class) VALUES (\"2\", \"AA Gun\", \"1\", \"1\", \"\", \"\")");
runQuery("INSERT INTO asset_type (asset_type_id, name, asset_category_id, visibility, order_seq, css_class) VALUES (\"3\", \"Airfield\", \"1\", \"1\", \"\", \"\")");
runQuery("INSERT INTO asset_type (asset_type_id, name, asset_category_id, visibility, order_seq, css_class) VALUES (\"4\", \"Radar\", \"1\", \"1\", \"\", \"\")");
runQuery("INSERT INTO asset_type (asset_type_id, name, asset_category_id, visibility, order_seq, css_class) VALUES (\"5\", \"Artillery\", \"1\", \"1\", \"\", \"\")");
runQuery("INSERT INTO asset_type (asset_type_id, name, asset_category_id, visibility, order_seq, css_class) VALUES (\"6\", \"Stug III\", \"2\", \"5\", \"\", \"vehicle\")");
runQuery("INSERT INTO asset_type (asset_type_id, name, asset_category_id, visibility, order_seq, css_class) VALUES (\"7\", \"Rifle Squad\", \"2\", \"5\", \"30\", \"\")");
runQuery("INSERT INTO asset_type (asset_type_id, name, asset_category_id, visibility, order_seq, css_class) VALUES (\"8\", \"Rifle Platoon\", \"2\", \"2\", \"20\", \"platoon\")");
runQuery("INSERT INTO asset_type (asset_type_id, name, asset_category_id, visibility, order_seq, css_class) VALUES (\"9\", \"Platoon Commander\", \"2\", \"5\", \"22\", \"\")");
runQuery("INSERT INTO asset_type (asset_type_id, name, asset_category_id, visibility, order_seq, css_class) VALUES (\"10\", \"HMG\", \"2\", \"5\", \"\", \"\")");
runQuery("INSERT INTO asset_type (asset_type_id, name, asset_category_id, visibility, order_seq, css_class) VALUES (\"11\", \"5.0cm PAK 38 Anti-tank Gun, with optional tow\", \"2\", \"5\", \"\", \"atg\")");
runQuery("INSERT INTO asset_type (asset_type_id, name, asset_category_id, visibility, order_seq, css_class) VALUES (\"12\", \"Company Commander\", \"2\", \"5\", \"12\", \"\")");
runQuery("INSERT INTO asset_type (asset_type_id, name, asset_category_id, visibility, order_seq, css_class) VALUES (\"13\", \"Company\", \"2\", \"1\", \"10\", \"company\")");
runQuery("INSERT INTO asset_type (asset_type_id, name, asset_category_id, visibility, order_seq, css_class) VALUES (\"14\", \"Factory\", \"1\", \"1\", \"\", \"\")");
runQuery("INSERT INTO asset_type (asset_type_id, name, asset_category_id, visibility, order_seq, css_class) VALUES (\"16\", \"Battalion\", \"2\", \"1\", \"\", \"battalion\")");
runQuery("INSERT INTO asset_type (asset_type_id, name, asset_category_id, visibility, order_seq, css_class) VALUES (\"17\", \"Battalion Commander\", \"2\", \"5\", \"\", \"\")");
runQuery("INSERT INTO asset_type (asset_type_id, name, asset_category_id, visibility, order_seq, css_class) VALUES (\"18\", \"SMG Squad\", \"2\", \"5\", \"30\", \"\")");
runQuery("INSERT INTO asset_type (asset_type_id, name, asset_category_id, visibility, order_seq, css_class) VALUES (\"19\", \"50mm Mortar\", \"2\", \"1\", \"\", \"\")");
runQuery("INSERT INTO asset_type (asset_type_id, name, asset_category_id, visibility, order_seq, css_class) VALUES (\"20\", \"HMG + Truck\", \"2\", \"5\", \"\", \"\")");
runQuery("INSERT INTO asset_type (asset_type_id, name, asset_category_id, visibility, order_seq, css_class) VALUES (\"21\", \"81mm Mortar + Truck\", \"2\", \"5\", \"\", \"\")");
runQuery("INSERT INTO asset_type (asset_type_id, name, asset_category_id, visibility, order_seq, css_class) VALUES (\"22\", \"75mm Recoiless Gun\", \"2\", \"5\", \"\", \"\")");
runQuery("INSERT INTO asset_type (asset_type_id, name, asset_category_id, visibility, order_seq, css_class) VALUES (\"23\", \"81mm Mortar\", \"2\", \"5\", \"\", \"\")");
runQuery("INSERT INTO asset_type (asset_type_id, name, asset_category_id, visibility, order_seq, css_class) VALUES (\"24\", \"120mm Mortar\", \"\", \"5\", \"\", \"\")");
runQuery("INSERT INTO asset_type (asset_type_id, name, asset_category_id, visibility, order_seq, css_class) VALUES (\"25\", \"PAK 40 Anti-Tank Gun with Tractor\", \"2\", \"5\", \"\", \"atg\")");
runQuery("INSERT INTO asset_type (asset_type_id, name, asset_category_id, visibility, order_seq, css_class) VALUES (\"26\", \"251/1 Half Track\", \"2\", \"5\", \"0\", \"vehicle\")");
runQuery("INSERT INTO asset_type (asset_type_id, name, asset_category_id, visibility, order_seq, css_class) VALUES (\"27\", \"Pz III\", \"2\", \"5\", \"0\", \"vehicle\")");
runQuery("INSERT INTO asset_type (asset_type_id, name, asset_category_id, visibility, order_seq, css_class) VALUES (\"28\", \"Regiment\", \"2\", \"1\", \"0\", \"regiment\")");
runQuery("INSERT INTO asset_type (asset_type_id, name, asset_category_id, visibility, order_seq, css_class) VALUES (\"29\", \"Division\", \"2\", \"1\", \"0\", \"division\")");
runQuery("DELETE t FROM channel t");
runQuery("INSERT INTO channel (channel_id, name, zone_id, faction_id) VALUES (\"1\", \"Allies\", \"0\", \"1\")");
runQuery("INSERT INTO channel (channel_id, name, zone_id, faction_id) VALUES (\"2\", \"Allies - Humber\", \"2\", \"1\")");
runQuery("INSERT INTO channel (channel_id, name, zone_id, faction_id) VALUES (\"3\", \"Allies - Jubilee\", \"4\", \"1\")");
runQuery("DELETE t FROM command t");
runQuery("INSERT INTO command (command_id, user_id, faction_id, name, seniority, map_id, parent_command_id, zone_id) VALUES (\"-1\", \"1\", \"0\", \"System\", \"0\", \"0\", \"\", \"\")");
runQuery("INSERT INTO command (command_id, user_id, faction_id, name, seniority, map_id, parent_command_id, zone_id) VALUES (\"1\", \"2\", \"1\", \"Lt. Col Orlov\", \"2\", \"1\", \"\", \"1\")");
runQuery("INSERT INTO command (command_id, user_id, faction_id, name, seniority, map_id, parent_command_id, zone_id) VALUES (\"2\", \"0\", \"2\", \"Oberstleutnant Schmidt\", \"2\", \"0\", \"14\", \"1\")");
runQuery("INSERT INTO command (command_id, user_id, faction_id, name, seniority, map_id, parent_command_id, zone_id) VALUES (\"3\", \"\", \"1\", \"Captain Ivanov\", \"3\", \"2\", \"1\", \"4\")");
runQuery("INSERT INTO command (command_id, user_id, faction_id, name, seniority, map_id, parent_command_id, zone_id) VALUES (\"4\", \"\", \"2\", \"Hauptmann Muller\", \"3\", \"2\", \"2\", \"4\")");
runQuery("INSERT INTO command (command_id, user_id, faction_id, name, seniority, map_id, parent_command_id, zone_id) VALUES (\"5\", \"\", \"1\", \"Captain Nachimovsky\", \"3\", \"0\", \"0\", \"3\")");
runQuery("INSERT INTO command (command_id, user_id, faction_id, name, seniority, map_id, parent_command_id, zone_id) VALUES (\"6\", \"\", \"2\", \"Hauptmann Ramcke\", \"3\", \"0\", \"2\", \"3\")");
runQuery("INSERT INTO command (command_id, user_id, faction_id, name, seniority, map_id, parent_command_id, zone_id) VALUES (\"8\", \"\", \"2\", \"Hauptmann Neufeldt\", \"3\", \"0\", \"16\", \"3\")");
runQuery("INSERT INTO command (command_id, user_id, faction_id, name, seniority, map_id, parent_command_id, zone_id) VALUES (\"10\", \"\", \"2\", \"Hauptmann Braun\", \"3\", \"0\", \"2\", \"2\")");
runQuery("INSERT INTO command (command_id, user_id, faction_id, name, seniority, map_id, parent_command_id, zone_id) VALUES (\"12\", \"\", \"2\", \"Leutnant Schmidt\", \"4\", \"0\", \"6\", \"3\")");
runQuery("INSERT INTO command (command_id, user_id, faction_id, name, seniority, map_id, parent_command_id, zone_id) VALUES (\"14\", \"\", \"2\", \"Oberst Weiss\", \"1\", \"0\", \"\", \"1\")");
runQuery("INSERT INTO command (command_id, user_id, faction_id, name, seniority, map_id, parent_command_id, zone_id) VALUES (\"16\", \"\", \"0\", \"Oberstleutnant Heinlein\", \"2\", \"0\", \"14\", \"1\")");
runQuery("DELETE t FROM event_type t");
runQuery("INSERT INTO event_type (event_type_id, name) VALUES (\"1\", \"Message\")");
runQuery("INSERT INTO event_type (event_type_id, name) VALUES (\"2\", \"Air Strike\")");
runQuery("INSERT INTO event_type (event_type_id, name) VALUES (\"3\", \"Artillery Strike\")");
runQuery("INSERT INTO event_type (event_type_id, name) VALUES (\"4\", \"Resupply\")");
runQuery("INSERT INTO event_type (event_type_id, name) VALUES (\"5\", \"Parachute Drop\")");
runQuery("INSERT INTO event_type (event_type_id, name) VALUES (\"6\", \"Combat Air Patrol\")");
runQuery("DELETE t FROM faction t");
runQuery("INSERT INTO faction (faction_id, name, game_id, faction_icon_id) VALUES (\"1\", \"Allies\", \"0\", \"4\")");
runQuery("INSERT INTO faction (faction_id, name, game_id, faction_icon_id) VALUES (\"2\", \"Axis\", \"0\", \"5\")");
runQuery("DELETE t FROM game t");
runQuery("DELETE t FROM map t");
runQuery("INSERT INTO map (map_id, name, width, height, background, x, y, scale, zone_id) VALUES (\"0\", \"Axe\", \"1280\", \"600\", \"map_4.jpg\", \"336\", \"49\", \"10\", \"5\")");
runQuery("INSERT INTO map (map_id, name, width, height, background, x, y, scale, zone_id) VALUES (\"1\", \"Overall\", \"1000\", \"620\", \"c1/map_0.jpg\", \"0\", \"0\", \"1\", \"1\")");
runQuery("INSERT INTO map (map_id, name, width, height, background, x, y, scale, zone_id) VALUES (\"2\", \"Kennet\", \"864\", \"432\", \"c1/map_1.jpg\", \"186\", \"392\", \"5\", \"3\")");
runQuery("INSERT INTO map (map_id, name, width, height, background, x, y, scale, zone_id) VALUES (\"3\", \"Jubilee\", \"648\", \"432\", \"c1/map_2.jpg\", \"430\", \"270\", \"5\", \"4\")");
runQuery("DELETE t FROM message t");
runQuery("INSERT INTO message (message_id, from_command_id, zone_id, content, channel_id, x, y, message_type_id, time_sent) VALUES (\"1\", \"1\", \"4\", \"No reinforcements currently available. Hold until further orders.\", \"3\", \"\", \"\", \"\", \"\")");
runQuery("INSERT INTO message (message_id, from_command_id, zone_id, content, channel_id, x, y, message_type_id, time_sent) VALUES (\"2\", \"3\", \"4\", \"Two German companies attacking with Stug. Losing Ground\", \"3\", \"500\", \"300\", \"7\", \"\")");
runQuery("INSERT INTO message (message_id, from_command_id, zone_id, content, channel_id, x, y, message_type_id, time_sent) VALUES (\"3\", \"1\", \"8\", \"High command is keen to construct a new bridge over the river, and want the area at Easy-Six surveyed by pioneers. The river is wide there and shallow, with a gravel bed, and it may be possible to cross there immediately (albeit a bit slowly), but even if it isn't, there are now British engineer teams with bridging equipment only a little to the rear which could advance and create a pontoon bridge very quickly. High Command is keen on this idea, because there are retreating Germans to the west of your map that could be cut off if a large armoured column could get across the Muhlbach by this evening. The bridges in the towns in this area are old stone bridges and not suited to very large armoured columns, and may be in uncertain hands and are in built-up areas which constrict movement\", \"2\", \"\", \"\", \"8\", \"\")");
runQuery("DELETE t FROM message_type t");
runQuery("INSERT INTO message_type (message_type_id, name) VALUES (\"1\", \"Reinforcement Request\")");
runQuery("INSERT INTO message_type (message_type_id, name) VALUES (\"2\", \"Support Request\")");
runQuery("INSERT INTO message_type (message_type_id, name) VALUES (\"3\", \"Objective Completed\")");
runQuery("INSERT INTO message_type (message_type_id, name) VALUES (\"4\", \"Objective Failed\")");
runQuery("INSERT INTO message_type (message_type_id, name) VALUES (\"5\", \"Reinforcements Arrived\")");
runQuery("INSERT INTO message_type (message_type_id, name) VALUES (\"6\", \"Forces Dispatched\")");
runQuery("INSERT INTO message_type (message_type_id, name) VALUES (\"7\", \"Sit Rep\")");
runQuery("INSERT INTO message_type (message_type_id, name) VALUES (\"8\", \"Briefing\")");
runQuery("DELETE t FROM model_type t");
runQuery("INSERT INTO model_type (model_type_id, name, m, ws, bs, s, t, w, i, a, ld, intel, cl, wp, description) VALUES (\"1\", \"Ork\", \"4\", \"3\", \"3\", \"3\", \"4\", \"1\", \"2\", \"1\", \"7\", \"6\", \"7\", \"7\", \"\")");
runQuery("INSERT INTO model_type (model_type_id, name, m, ws, bs, s, t, w, i, a, ld, intel, cl, wp, description) VALUES (\"2\", \"Marine\", \"4\", \"4\", \"4\", \"4\", \"4\", \"1\", \"4\", \"1\", \"8\", \"8\", \"8\", \"8\", \"\")");
runQuery("DELETE t FROM morale t");
runQuery("INSERT INTO morale (morale_id, name, rules) VALUES (\"1\", \"Green\", \"\")");
runQuery("INSERT INTO morale (morale_id, name, rules) VALUES (\"2\", \"Regular\", \"\")");
runQuery("INSERT INTO morale (morale_id, name, rules) VALUES (\"3\", \"Veteran\", \"\")");
runQuery("DELETE t FROM user t");
runQuery("INSERT INTO user (user_id, username, guid) VALUES (\"1\", \"admin\", \"aaa\")");
runQuery("INSERT INTO user (user_id, username, guid) VALUES (\"2\", \"monty\", \"bbb\")");
runQuery("DELETE t FROM z_z t");
runQuery("DELETE t FROM zone t");
runQuery("INSERT INTO zone (zone_id, game_id, zone_type_id, name, x, y, map_id, parent_zone_id, width, height, scale) VALUES (\"1\", \"10\", \"1\", \"Battlefield\", \"0\", \"0\", \"0\", \"\", \"\", \"\", \"1\")");
runQuery("INSERT INTO zone (zone_id, game_id, zone_type_id, name, x, y, map_id, parent_zone_id, width, height, scale) VALUES (\"2\", \"10\", \"2\", \"Humber\", \"450\", \"120\", \"1\", \"1\", \"86\", \"129\", \"5\")");
runQuery("INSERT INTO zone (zone_id, game_id, zone_type_id, name, x, y, map_id, parent_zone_id, width, height, scale) VALUES (\"3\", \"10\", \"2\", \"Kennet\", \"186\", \"392\", \"1\", \"1\", \"172\", \"86\", \"5\")");
runQuery("INSERT INTO zone (zone_id, game_id, zone_type_id, name, x, y, map_id, parent_zone_id, width, height, scale) VALUES (\"4\", \"10\", \"2\", \"Jubilee\", \"430\", \"270\", \"1\", \"1\", \"129\", \"86\", \"5\")");
runQuery("INSERT INTO zone (zone_id, game_id, zone_type_id, name, x, y, map_id, parent_zone_id, width, height, scale) VALUES (\"5\", \"10\", \"2\", \"Axe\", \"580\", \"180\", \"1\", \"1\", \"86\", \"86\", \"5\")");
runQuery("INSERT INTO zone (zone_id, game_id, zone_type_id, name, x, y, map_id, parent_zone_id, width, height, scale) VALUES (\"7\", \"10\", \"0\", \"Reserve Area A\", \"200\", \"150\", \"1\", \"1\", \"\", \"\", \"5\")");
runQuery("INSERT INTO zone (zone_id, game_id, zone_type_id, name, x, y, map_id, parent_zone_id, width, height, scale) VALUES (\"8\", \"10\", \"2\", \"Dee\", \"240\", \"200\", \"1\", \"1\", \"86\", \"172\", \"5\")");
runQuery("INSERT INTO zone (zone_id, game_id, zone_type_id, name, x, y, map_id, parent_zone_id, width, height, scale) VALUES (\"9\", \"10\", \"\", \"Reserve Area B\", \"80\", \"350\", \"1\", \"1\", \"\", \"\", \"5\")");
runQuery("INSERT INTO zone (zone_id, game_id, zone_type_id, name, x, y, map_id, parent_zone_id, width, height, scale) VALUES (\"15\", \"10\", \"\", \"\", \"0\", \"0\", \"\", \"\", \"\", \"\", \"\")");
runQuery("DELETE t FROM zone_type t");
runQuery("INSERT INTO zone_type (zone_type_id, name, icon) VALUES (\"1\", \"Area\", \"\")");
runQuery("INSERT INTO zone_type (zone_type_id, name, icon) VALUES (\"2\", \"Battlefield\", \"\")");
runQuery("INSERT INTO zone_type (zone_type_id, name, icon) VALUES (\"3\", \"Feature\", \"\")");
runQuery("INSERT INTO zone_type (zone_type_id, name, icon) VALUES (\"4\", \"Bridge\", \"4_16.png\")");
runQuery("INSERT INTO zone_type (zone_type_id, name, icon) VALUES (\"5\", \"Airfield\", \"\")");
runQuery("INSERT INTO zone_type (zone_type_id, name, icon) VALUES (\"6\", \"AA Emplacement\", \"\")");
runQuery("INSERT INTO zone_type (zone_type_id, name, icon) VALUES (\"7\", \"Radar\", \"\")");
runQuery("UPDATE game SET last_updated=NOW()");
function runQuery($strSql){
    if (mysql_query($strSql)) {echo "Ran query" . $strSql . "<br>";}
    else {echo "Error running query: " . mysql_error() . "<br>";}
}
?>
